### ISSUE TITLE
403 On Search

### ISSUE THREAD

**Issue by lukepolo** [spatie/googlesearch#10]
Sadly im getting a 403, and its not being caught. 

![screen shot 2016-03-03 at 11 14 12 am](https://cloud.githubusercontent.com/assets/2066668/13500561/17e76588-e131-11e5-8959-35a1c9d9f2bf.png)

**Comment by freekmurze** [comment]
That's not so good. Thanks for bringing it to my attention. I'll take a look at it when I have the time. If you need this fixed soon, submit a PR.

**Comment by lukepolo** [comment]
NP, ill look at it soon, have another problem that came up after that :-1:

**Comment by rkeppner** [comment]
I was digging around in the code, trying to figure out why I couldn't get it to work. Found I was getting a 403 error returned in the XML from Google CSE, so I added just enough code to catch it. #11

In reading through [Google's docs](https://developers.google.com/custom-search/docs/api#overview), it seems that my biggest issue is that I need to pay them instead of using the free version:

> Use the Google WebSearch service to retrieve results in XML format. (Note: This service is available only to customers of Google Site Search.)
