### ISSUE TITLE
[question] what schema.org i must pick to get 42

### ISSUE THREAD

**Issue by rebornishard** [spatie/googlesearch#16]
Hello spatie,

thanks for great code,
sorry for asking in here, since google search become google custom search api
i didn't know which scema.org i must pick to get result : 42

`$searchResults = GoogleSearch::getResults('The meaning of life');`

i got 403 xml error with laravel 5.2

thanks

**Comment by freekmurze** [comment]
That query and result for docs is just a fictional example.

Did you specify a valid search engine id in the `searchEngineId` of the config file of this package?

**Comment by Mirza-Obaid** [comment]
i am also stuck in same problem i specified engine id also

**Comment by AlexVanderbist** [comment]
Hi, 

The Google Custom Search (or cse) is a service to search through your own site, not all Google results. Since the "what is the meaning of life" easter egg is only a part of the global Google search results, it'll never show up in your custom search engine.

The `XML indicated service error: 403` (forbidden) exception indicates you are using the free version of Google Custom Search. This package works via the cse API's XML output which is only available to paying users.

Good luck!
